package com.busfinder.busai;

import java.util.List;

import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

@RestController
public class OllamaController {

    private final OllamaService ollamaService;
    private final BusService busService;
    private final ObjectMapper objectMapper;

    public OllamaController(
            OllamaService ollamaService,
            BusService busService,
            ObjectMapper objectMapper) {

        this.ollamaService = ollamaService;
        this.busService = busService;
        this.objectMapper = objectMapper;
    }

    @PostMapping("/ai-search")
    public List<Bus> aiSearch(@RequestBody AiSearchRequest request) {

        try {

            // 1. Send user's natural language to Ollama
            String ollamaResponse =
                    ollamaService.askOllama(request.getMessage());

            // 2. Read Ollama response
            JsonNode root = objectMapper.readTree(ollamaResponse);

            // 3. Extract the JSON generated by Ollama
            String aiJson = root.path("response").asText();

            // 4. Convert AI JSON into SearchRequest
            SearchRequest searchRequest =
                    objectMapper.readValue(aiJson, SearchRequest.class);

            // 5. Search buses using extracted filters
            return busService.searchBuses(
                    searchRequest.getSource(),
                    searchRequest.getDestination(),
                    searchRequest.getStartTime(),
                    searchRequest.getEndTime(),
                    searchRequest.getBusType()
            );

        } catch (Exception e) {

            throw new RuntimeException(
                    "AI bus search failed: " + e.getMessage()
            );
        }
    }
}